### ISSUE TITLE
AMP support for blog posts

### ISSUE THREAD

**Issue by krtek** [fragaria/website#5]
It would be nice to have an AMP blog version.

**Comment by JirkaChadima** [comment]
It seems fairly easy with [amp-jekyll](https://github.com/juusaw/amp-jekyll), see `feat/amp-support` branch. The only thing is that the markdown output is somehow crippled.

**Comment by krtek** [comment]
Good catch! 🐟 
The markdown was crippled because there was no correct `amp` template. I added one and now we *just* have to put something to `<style>` section.
